name: GitHub Profile 3D Contrib

on:
  push:
    branches:
      - main  # ou qualquer branch que você deseja

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: GitHub-Profile-3D-Contrib
        uses: yoshi389111/github-profile-3d-contrib@0.9.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
