name: GitHub Profile 3D Contrib

on:
  push:
    branches:
      - main  # Ou a branch que você deseja

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub-Profile-3D-Contrib
        uses: yoshi389111/github-profile-3d-contrib@0.9.0
