name: Generate Snake Game from GitHub Contribution Grid

on:
  schedule:
    - cron: "0 0 * * *"  # Atualiza diariamente à meia-noite
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate Snake Game from GitHub contribution grid
        uses: Platane/snk@master
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/github-snake.svg

      - name: Push Snake Game to the repository
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Generated Snake Game from Contribution Grid"
          git push
