name: GitHub-Profile-3D-Contrib

on:
  schedule: # 03:00 JST == 18:00 UTC
    - cron: "0 18 * * *"
  workflow_dispatch:  # Permite executar manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v4  # Certifique-se de usar a versão correta
      - uses: yoshi389111/github-profile-3d-contrib@latest
        env:
          GITHUB_TOKEN: ${{ secrets.MY_PERSONAL_ACCESS_TOKEN }}  # Usando o novo token
          USERNAME: ${{ github.repository_owner }}  # Nome de usuário do repositório
      - name: Set up Git credentials
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git config --global credential.helper 'store --file=.git-credentials'
          echo "https://x-access-token:${{ secrets.MY_PERSONAL_ACCESS_TOKEN }}@github.com" > .git-credentials
      - name: Commit & Push
        run: |
          git add -A .
          if git commit -m "generated"; then
            git push
          fi
